### ISSUE TITLE
Performance: Speckle Serialiser takes too long to complete

### ISSUE THREAD

**Issue by alelom** [BHoM/Speckle_Toolkit#49]
#### Description:

Speckle_Serialiser is responsible for almost all computation time while performing the Push. We're talking several seconds per <10 `Structure.Bar`s. I suspect it's due to a limitation of how speckle does its "serialisation" together with the deep nesting of our objects, which probably Speckle wasn't designed for. 
SpeckleSerialiser does in fact expose a `maximumNestLevel` parameter, which we cannot afford to use as we need to send eveything. (Edit: changing it does not seem to do anything).

Already highlighted the issue to Dimitri. I need to produce more detailed profiling; based on that potentially raise an issue in their Github. 

In the meantime, perhaps #58 could help.

**Comment by alelom** [comment]
As mentioned here: https://github.com/BHoM/Speckle_Toolkit/pull/53#issuecomment-582898846
You can find a test in the Push method in [this branch](https://github.com/BHoM/Speckle_Toolkit/tree/%2358-BranchFrom%2346-MultithreadingTests) that (predictabily) demonstrates that neither Tasks or Parallelisation help in improving the performance of SpeckleSerialiser _consistently_.

**Comment by alelom** [comment]
Tried the thing explained in my previous comment.
The nesting level does not seem to do anything significant with regards to speed (or anything at all).

Only thing that is left to do is expose an option that allows the user to choose whether to Push with the SpeckleSerialiser or with our serialiser. Our serialiser is ~100 faster, but we lose the ability to filter/group per BHoMObject property in the SpeckleViewer.

**Comment by didimitrie** [comment]
Yep, true, i can definitively reproduce; but this is always going to be an issue using the speckle abstract route because of all the home brew reflection involved.

![image](https://user-images.githubusercontent.com/7696515/73954845-4da67580-48fa-11ea-849e-fccaa99919e5.png)

the c# component just calls `JsonConvert.Serlialize(x)` for reference. 

Speckle's serialiser is geared towards serialising Speckle objects after all; the abstract route is a convenient way of testing things without creating a full blown speckle kit.

**Comment by didimitrie** [comment]
I've tested making the root bhom object class inherit from the speckle object class, **effectively transforming the whole of the bhom object model into a pseudo-speckle kit** (for fun and giggles, as they say). 

```
namespace BH.oM.Base
{
    // -------------------------------v   PANIC TIME
    public class BHoMObject : SpeckleObject, IBHoMObject
    {
        public Guid BHoM_Guid { get; set; } = Guid.NewGuid();
// ...
```

There's some objects, namely geometry constructs, that do not inherit from it - which was weird. I've made them inherit from the Bhom object base class too for giggles. This effectively allowed Core, with some minor modifications, to see bhom objects as native speckle objects :) 

Serialisation time, in this case, is quite improved of course:

![image](https://user-images.githubusercontent.com/7696515/73963117-9d3f6e00-4907-11ea-9fa6-42c36870e849.png)

Everything's red as there's missing conventions coming from speckle that are not implemented in Bhom. Just leaving this here - imho this route is a much better integration (especially since everything else in BHoM land is working perfectly fine).

**Comment by alelom** [comment]
Thanks @didimitrie .

Before your latest comment, I "solved" this by [re-writing the Speckle `Serialise` method](https://github.com/BHoM/Speckle_Toolkit/pull/53/commits/7e1e344c25f33ebfcf7545d92e0a127d5c603ee0#r375987029) in its "Essential" parts, so it does the bare minimum I need to get the objects "filterable by property" in the SpeckleViewer.
Then the actual BHoMObject data is serialised (fast) with our serialiser, and stored in the resulting top-level abstract object (in its `Property` field).

This allows to get both features in (SpeckleViewer to "digest" the objects, and the full bhom object to be serialised/deserialised fast).

Tomorrow I'll review your last comment and let you know my thoughts about that. Cheers!

**Comment by alelom** [comment]
> I've tested making the root bhom object class inherit from the speckle object class, **effectively transforming the whole of the bhom object model into a pseudo-speckle kit** (for fun and giggles, as they say).

I loved the PANIC TIME code remark 🤣 

> There's some objects, namely geometry constructs, that do not inherit from it - which was weird. I've made them inherit from the Bhom object base class too [...]

I completely agree that's weird. However they are reasons for that. I had advocated in the past for a different solution, but that's what we're sticking to. Your comment is precious to me as it's proving my point of back then.
 
> imho this route is a much better integration (especially since everything else in BHoM land is working perfectly fine).
This I am not sure though. This would require literally all repos of BHoM to depend on Speckle.  In principle I would have absolutely nothing against that! However, this choice would rightly need a justification – so far this would benefit only a limited number of repos, namely one: Speckle_Toolkit.
