### ISSUE TITLE
Ambiguous reference leading to build errors

### ISSUE THREAD

**Issue by izzylys** [BHoM/Speckle_Toolkit#70]
#### Description:
Getting a build error in `Speckle_Adapter/CreateIBHoMObjects.cs` due to an ambiguous reference between `BH.Engine.Speckle.Compute` and `BH.Engine.Rhinoceros.Compute`

This is a 2 sec simple fix -- will do now.

#### Steps to reproduce:
Build the project in Visual Studio.

**Comment by alelom** [comment]
Thanks @izzylys ! Consider that the master branch is now quite old and there's a long-standing open PR open that might be more up-to-date and not showing such errors (not sure however).
The reason the PR is long standing is because we're waiting some work on the main SpeckleCore and SpeckleServer repos to settle down.

**Comment by izzylys** [comment]
ok sounds good! I was just wanting to test something out when I noticed the build error. if I want to play around a bit, which branch should I use -- branch #714?

**Comment by alelom** [comment]
Yes please! If you need anything you find me on slack too

**Comment by alelom** [comment]
Sorry @izzylys  I realised I didn't open the PR yet with that branch - doing it now as there are dependent branches you need to switch to!

**Comment by izzylys** [comment]
fab, thank you!!
